# --- Main Settings ---
font=JetBrains Mono:size=14
dpi-aware=auto

horizontal-pad=10
vertical-pad=10
inner-pad=5

[colors]
; background=#1a1b26fa
; text=#414868ff
; match=#f7768eff
; selection=#41486800
; selection-text=#c0caf5ff
; selection-match=#9ece6aff
border=#c0caf500
; prompt=#9ece6aff
; input=#c0caf5ff
; message=#7aa2f7ff


# --- Border Settings ---
[border]
radius=10
