# Appearance

font pango:JetBrainsMono Nerd Font 8

# Borders
default_border pixel 0
for_window [class="^.*"] border pixel 0
for_window [app_id="^.*"] border pixel 0

# Colors            border   background text     indicator child_border
# client.focused			#c0caf5  #c0caf5    #c0caf5  #c0caf5   #c0caf5
client.focused		#414868  #414868    #414868  #414868   #414868
client.unfocused		#414868  #414868    #414868  #414868   #414868
# client.urgent     #f7768e  #f7768e    #f7768e  #f7768e   #f7768e

# Gaps
gaps inner 5
gaps outer 0

# Status bar
bar {
	swaybar_command waybar
}
