# Autostart
exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec export XDG_CURRENT_DESKTOP=sway

# Start the gnome keyring daemon for secrets management
exec /usr/bin/gnome-keyring-daemon --start --components=secrets
exec dex --autostart --environment sway
exec nm-applet

# Update notifications
exec notify-update

# Cava
exec_always pkill -x cava; cava -p ~/.config/cava/config &

# Conky
# exec_always pkill conky 
# exec_always sleep 2 && env -u DISPLAY conky -c ~/.config/conky/ram.lua

# Keyboard remapping
exec xremap ~/.config/xremap/config.yml

# Clipboard manager
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store

# Night light
exec wlsunset -T 6500 -t 3000 -l 14.6 -L 121.0

# Swaync Notifications
# exec_always --no-startup-id pkill swaync; swaync &
