# Autostart

exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec_always export XDG_CURRENT_DESKTOP=sway

exec --no-startup-id /usr/bin/gnome-keyring-daemon --start --components=secrets
exec --no-startup-id dex --autostart --environment sway
exec --no-startup-id nm-applet

exec_always --no-startup-id notify-update
exec_always --no-startup-id pkill -x cava; cava -p ~/.config/cava/config &
# exec_always pkill conky
# exec_always --no-startup-id sleep 2 && env -u DISPLAY conky -c ~/.config/conky/conky.conf

exec xremap ~/.config/xremap/config.yml

# Clipboard manager
exec_always wl-paste --type text --watch cliphist store
exec_always wl-paste --type image --watch cliphist store
