# Keybindings

# Terminal
bindsym $mod+Return exec $term
bindsym $mod+Shift+Return exec $term2

# Kill focused window
bindsym $mod+q kill
bindsym $mod+BackSpace kill

# Focus
bindsym Mod1+Tab    focus right
bindsym $mod+Left   focus left
bindsym $mod+Down   focus down
bindsym $mod+Up     focus up
bindsym $mod+Right  focus right
bindsym $mod+j      focus left
bindsym $mod+k      focus down
bindsym $mod+i      focus up
bindsym $mod+l      focus right

# Move focused window
bindsym $mod+Shift+Left  move left
bindsym $mod+Shift+Down  move down
bindsym $mod+Shift+Up    move up
bindsym $mod+Shift+Right move right

# Splits
bindsym $mod+h split h
bindsym $mod+v split v

# Fullscreen
bindsym $mod+Shift+f fullscreen toggle

# Floating
bindsym $mod+f floating toggle
bindsym $mod+a focus parent

# Layout
bindsym $mod+t layout toggle split

# Reload config
bindsym $mod+Shift+c reload

# Scratchpad
bindsym $mod+m       move scratchpad
bindsym $mod+Shift+m scratchpad show

# Screenshot
bindsym $mod+Shift+s exec --no-startup-id screenshot

# Clipboard
bindsym $mod+Shift+v exec clipboard

# Fuzzel launchers
bindsym $mod+Shift+p exec fuzzel-media
bindsym Mod1+F4      exec fuzzel-power
bindsym $mod+Tab     exec fuzzel-window
bindsym $mod+Space   exec fuzzel

# Volume
bindsym --locked XF86AudioRaiseVolume exec volume up
bindsym --locked XF86AudioLowerVolume exec volume down
bindsym --locked XF86AudioMute        exec volume mute

# Resize mode
mode "resize" {
	bindsym j resize shrink width  1 px or 1 ppt
	bindsym k resize grow   height 1 px or 1 ppt
	bindsym i resize shrink height 1 px or 1 ppt
	bindsym l resize grow   width  1 px or 1 ppt

	bindsym Left  resize shrink width  1 px or 1 ppt
	bindsym Down  resize grow   height 1 px or 1 ppt
	bindsym Up    resize shrink height 1 px or 1 ppt
	bindsym Right resize grow   width  1 px or 1 ppt

	bindsym $mod+Left  focus left
	bindsym $mod+Down  focus down
	bindsym $mod+Up    focus up
	bindsym $mod+Right focus right

	bindsym $mod+j focus left
	bindsym $mod+k focus down
	bindsym $mod+i focus up
	bindsym $mod+l focus right

	bindsym Return    mode "default"
	bindsym Escape    mode "default"
	bindsym Space     mode "default"
	bindsym $mod+r    mode "default"
}

bindsym $mod+r mode "resize"
