# SWAYFX CONFIGURATION

# Corners
corner_radius 6

# Shadows
shadows enable
shadows_on_csd enable

# Dim inactive windows
default_dim_inactive 0.25
dim_inactive_colors.unfocused #000000BF

# Layer effects

# for fuzzel launcher
layer_effects "launcher" { 
  shadows enable
	corner_radius 6
}

# for mako notifications
# layer_effects "notifications" { 
#   shadows enable
# 	corner_radius 6
# }
