#!/bin/bash

entries="Lock\nSuspend\nLogout\nReboot\nShutdown"

selected=$(echo -e "$entries" | fuzzel --dmenu --mesg "Power Menu" --message-color '#f7768eff' --lines 5 --anchor=top-right --y-margin=3 --x-margin=2  --width=10)

case "$selected" in
  Lock)
    swaylock -f -c 000000
    ;;
  Suspend)
    systemctl suspend
    ;;
  Logout)
    swaymsg exit
    ;;
  Reboot)
    reboot
    ;;
  Shutdown)
    shutdown now
    ;;
esac
