#!/bin/bash

entries="Lock\nSuspend\nLogout\nReboot\nShutdown"

selected=$(echo -e "$entries" | fuzzel --dmenu --mesg "Power Menu" --lines 5 --anchor=top-right --y-margin=-1 --x-margin=1 --width=14)

case "$selected" in
  Lock)
    swaylock -f -c 000000
    ;;
  Suspend)
    systemctl suspend
    ;;
  Logout)
    swaymsg exit
    ;;
  Reboot)
    reboot
    ;;
  Shutdown)
    shutdown now
    ;;
esac
